server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
