server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: discovery
      port: ${DISCOVERY_PORT}
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: http://auth:${AUTH_PORT}
          predicates:
            - Path=/api/v1/auth/**