server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway

  cloud:
    # Discovery Configuration
    consul:
      host: ${DISCOVERY_URL:localhost}
      port: ${DISCOVERY_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${random.value}

    # Gateway Configuration
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: http://${AUTH_URL}:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: Frontend
          uri: http://${FRONTEND_URL}:3000
          predicates:
            - Path=/**
