server:
  port: ${AUTH_PORT}

spring:
  application:
    name: auth

  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

  rabbitmq:
    host: rabbitmq

  datasource:
    url: jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    database: "postgresql"
    show-sql: false
    hibernate:
      ddl-auto: validate