server:
  port: 8081

spring:
  application:
    name: auth

  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate
