server:
  port: ${PORT:8080}

spring:
  application:
    name: blueprint
  resources:
    add-mappings: false

  # Database
  datasource:
    url: "jdbc:postgresql://${BLUEPRINT_DB_URL:localhost:5432}/${BLUEPRINT_DB_NAME:postgres}"
    username: ${BLUEPRINT_DB_USERNAME:postgres}
    password: ${BLUEPRINT_DB_PASSWORD:""}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate

  # Session
  session:
    store-type: redis
  redis:
    host: ${REDIS_URL:localhost}
    port: ${REDIS_PORT:6379}

  # Message-Broker
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}

  # Discovery
  cloud:
    consul:
      host: ${DISCOVERY_URL:localhost}
      port: ${DISCOVERY_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}